### PR TITLE
HTML, CSS and live demo link

### PR DESCRIPTION
**Pull request by JuanLPalacios**
### changes

- add index.html with title, add to readme.md more information
- add css/main.css to turn title green
- add test.md( and .gitignore rule)
- lint fixes

### CODE REVIEW

**Review by DammyShittu — CHANGES_REQUESTED** [review]
Hi @JuanLPalacios , 

Good job so far!

There are some issues that you still need to work on to go to the next project but you are almost there! 

# Required Changes ♻️

- Kindly add the [HTML and CSS Linters](https://github.com/microverseinc/linters-config) as indicated in the requirements. [Linters](https://en.wikipedia.org/wiki/Lint_(software)) are really helpful tools as they help you catch bugs, detect errors with stylings, and also follow best practices. 😉 

- Descriptive commit messages are great to help anyone going through your code know the work that was done at that particular checkpoint. Kindly go through this [article](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) to learn more about writing more descriptive commit messages 👍 

# Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by JuanLPalacios** [comment]
@DammyShittu Are these commit messages better?

**Comment by DammyShittu** [comment]
Hi @JuanLPalacios,

Yes, they are.  Well done 👍 

Cheers 🚀

**Review by micheaol — APPROVED** [review]
# STATUS: APROVED :green_circle: :clap: 
Hi @JuanLPalacios , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥇 
Congratulations! 🎉 

well-1

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
